### ISSUE TITLE
bottom nav bar

### ISSUE THREAD

**Issue by lhao03** [UBC-BEST/deprecated-frontend-m2m#2]
progress:
- default home page has been added

todo:
- ~build a bottom navigation bar that can navigate to three screens.~
- feel free to use mock data
- set up a call with me (find the link on our slack channel) if you need 

deliverable:
- demo

default:
![image](https://user-images.githubusercontent.com/55033656/111874922-cdf03480-895c-11eb-88cc-8a77d3e16176.png)

what we want it to look like: 
![image](https://user-images.githubusercontent.com/55033656/111874914-c892ea00-895c-11eb-9b66-206019620250.png)

To grab the default page, pull from https://github.com/UBC-BEST/frontend-m2m/tree/auth-wip

**Comment by YaraNasrallah** [comment]
This might be useful. I've been using these sites as guided learning for Kotlin & Bottom Nav Bars:
https://www.geeksforgeeks.org/bottom-navigation-bar-in-android/
https://code.tutsplus.com/tutorials/how-to-code-a-bottom-navigation-bar-for-an-android-app--cms-30305

**Comment by lhao03** [comment]
will merge with this: 
https://github.com/YaraNasrallah/BottomNavigationBar

**Comment by lhao03** [comment]
![Screenshot_20210410-161726_M2M.jpg](https://user-images.githubusercontent.com/55033656/114285945-41dfa300-9a18-11eb-8918-1e663a56cfa5.jpg)![Screenshot_20210410-161724_M2M.jpg](https://user-images.githubusercontent.com/55033656/114285955-4441fd00-9a18-11eb-96a6-81511f88d613.jpg)
